auto            {return AUTO;           }
register        {return REGISTER;       }
static          {return STATIC;         }
extern          {return EXTERN;         }
typedef         {return TYPEDEF;        }
void            {return VOID;           }
char            {return CHAR;           }
short           {return SHORT;          }
int             {return INT;            }
long            {return LONG;           }
float           {return FLOAT;          }
double          {return DOUBLE;         }
signed          {return SIGNED;         }
unsigned        {return UNSIGNED;       }
struct          {return STRUCT;         }
union           {return UNION;          }
const           {return CONST;          }
volatile        {return VOLATILE;       }
sizeof          {return SIZEOF;         }
enum            {return ENUM;           }
case            {return CASE;           }
default         {return DEFAULT;        }
if              {return IF;             }
switch          {return SWITCH;         }
while           {return WHILE;          }
do              {return DO;             }
for             {return FOR;            }
goto            {return GOTO;           }
continue        {return CONTINUE;       }
break           {return BREAK;          }
return          {return RETURN;         }
